### ISSUE TITLE
Demo 2 Booking

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/team-admin#10]
> The demo bookings will open at 09:00 on 9 April and close at 09:30 on 11 April.
> 
> It came to our attention that the booking slots were accessible the past few days. Bookings that were made have been unbooked.

**Comment by FJMentz** [comment]
Can we book again for 11:20 (same time as first demo)?

**Comment by egeldenhuys** [comment]
@FJMentz Will you be able to book for us?

**Comment by FJMentz** [comment]
Will do so!

**Comment by egeldenhuys** [comment]
Thank you!

**Comment by egeldenhuys** [comment]
11:25 - 11:50, booked by @FJMentz
