### ISSUE TITLE
Client Parking Access

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/team-admin#11]
> You should have regular discussions with your client.  Seek their approval of all artefacts
> that we require for COS 301.
> Your client is welcome to attend your demo, but it is not required.  Ideally you should
> arrange to see your client for an additional half hour or more before or after your demo.
> The demo itself may be rushed and can not serve as an opportunity for you to ask your
> client some questions.
> If your client needs access to campus – for the demo or any other meeting, please provide
> the following detail at least 36 hours before the time.
> • Client Name
> • Date
> • Time
> • Venue
> • Vehicle description
> • Vehicle registration number.

**Comment by FJMentz** [comment]
Will Talk to Jason tomorrow to get all the details from them.
