### ISSUE TITLE
Project Repository Structure

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/team-admin#15]
To aid in consolidating the project I have the following suggestion:

Repositories:
- `docks` - The entry point. Contains a README with links to all relevant resources and information. Slack, Waffle, Documentation, Travis CI, Docker Hub. Everything from the Landing page, but in Markdown. It will also include an automated report to summarise contributions from all our repositories, and all our branches. This repo should contain everything to put together a working demo of the project.
- `docks-api` - Rename `docks`
- `docks-ui` - Docks dashboard

Repository Changes:
- `docs` - Move documentation to `docks` and delete
- `team-admin` - Delete or make private
- `docs-bin` - Store the binaries somewhere else that will have a static link for the latest versions
- `docks-demo` - Delete. Purpose will be replaced by `docks`

### Automated Contribution Report
This can be generated by Travis CI. Commits are to all branches.

#### Data
| Contributor | Commits to `docks` | commits to `docs-api` | commits to `docs-ui` | Total commits |
| -------------- | ------------------------- | --------------------------- | -------------------------- | ------------------ |
| Evert Geldenhuys (@egeldenhuys) | 4 | 3 | 0 | 7 |

#### Views
- Past Week
- Past Month
- Since previous demo
- Total

----
**EDIT**: Add note about deleting `docks-demo`

**Comment by devosray** [comment]
This seems like a great suggestion :+1: 

We'll meet with Stacey and see if this will work for her.

**Comment by egeldenhuys** [comment]
We can even market the report generator for the Lecturers to assist in future marking of 301 teams.

**Comment by egeldenhuys** [comment]
The above plan has been implemented. We can also use the `docks` repo for GitHub Pages
