### ISSUE TITLE
Demo 1 Review

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/team-admin#4]
- What worked well for the sprint?
- What did not work out well?
- Why did these things not work?
- What can we do differently next time?

**Comment by devosray** [comment]
For one, we didn't have a proper sprint at all. Just a vague "this needs to be done.. who can do it?" We should meet up and start a proper sprint. Maybe not to do a large amount of work, but to start the process of having regular sprints as well as scrums.

**Comment by egeldenhuys** [comment]
After meeting with Jason we will have to review our architecture as a team and from there we can organise a sprint.

Next time I suggest we do the following:
- Allocate all tasks - Everyone knows what they should be working on. There will be freedom to choose initially. It does not work well when the project is run like an open source project.
- During a presentation everyone should get a turn to speak - to show understanding
- Finish tasks at least a day before the hard deadline. Finishing tasks 30 minutes before the demo was too bleeding edge for me. However given the short time frame and semester tests I am more lenient this time.

Perhaps sub deadlines such as:
1. Angular Hello world
2. GET request
3. Displaying a list of running containers
4. Stopping a container from the list
