### ISSUE TITLE
Workflow Document

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/team-admin#5]
- Git and GitHub workflows
- Conventions and Standards
- Purpose of different communication channels

**Comment by EmpireMuncher** [comment]
Can you elaborate more on what this issue is? Is it concerning the format and place we put it in or is it more related to actually putting this together?

**Comment by egeldenhuys** [comment]
For git workflows we need to agree on the following
- Git flow workflow
- Branch name convention: `<description>-#<issue_number>`
- When to squash, rebase or merge commit

For GitHub workflow:
- Pull request review process

Then also document any standards and conventions in the document as well.
The issue relates to the contents of the document to be discussed.

**Comment by FJMentz** [comment]
Can we please discuss this in Monday's meeting (26/03)

**Comment by egeldenhuys** [comment]
Pull request reviews

Feature -> develop (2 reviews)
develop -> master (team meeting)

**Comment by egeldenhuys** [comment]
Standards will be introduced based on he technology used.
