### ISSUE TITLE
Rename "admin" repo to "team"

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/team-admin#6]
Since this repository seems to be used for for discussing the team workflow and team related tasks, I think the name `team` would be more clear regarding the purpose.

Consensus?

**Comment by devosray** [comment]
`team admin` maybe?

**Comment by EmpireMuncher** [comment]
Agree with above @devosray.

> team admin

**Comment by egeldenhuys** [comment]
Renamed to `team-admin` will update any hooks
