### ISSUE TITLE
Docker Hub organisation

### ISSUE THREAD

**Issue by egeldenhuys** [TripleParity/team-admin#8]
Used for hosting of our images. Will look into making the account an organisation.

**Comment by egeldenhuys** [comment]
`tripleparity` is now an organisation. You will need to create an [Docker Hub](https://hub.docker.com/) account to be able to make changes in the org.

**Comment by FJMentz** [comment]
Do you need to subscribe to the org?

**Comment by egeldenhuys** [comment]
I have configured it to automatically build images as we push to `docks` and `docks-ui`

If you have a Docker Hub account let me know so I can add you to the Docker Hub organisation to allow you to make changes in the org.

**Comment by FJMentz** [comment]
Can I ask for clarification on what Dockerhub does so that everyone understands? 

Does it only create and host the images or how exactly does it work?

Also how will this benefit is?

**Comment by egeldenhuys** [comment]
> Docker Hub is a cloud-based registry service which allows you to link to code repositories, build your images and test them, stores manually pushed images, and links to Docker Cloud so you can deploy images to your hosts. It provides a centralized resource for container image discovery, distribution and change management, user and team collaboration, and workflow automation throughout the development pipeline.

-- https://docs.docker.com/docker-hub/

> You can build your images automatically from a build context stored in a repository. A build context is a Dockerfile and any files at a specific location. For an automated build, the build context is a repository containing a Dockerfile.
> 
> Automated Builds have several advantages:
> - Images built in this way are built exactly as specified.
> - The Dockerfile is available to anyone with access to your Docker Hub repository.
> - Your repository is kept up-to-date with code changes automatically.

-- https://docs.docker.com/docker-hub/builds/

Docker Hub will create our images and host them. It allows anyone to run our service with `docker run tripleparity/docks`

**Comment by FJMentz** [comment]
Thank you very much @egeldenhuys for that! 👍
